### ISSUE TITLE
Training?

### ISSUE THREAD

**Issue by willianpripp** [ha-ha-ha-han/UKBiobank_deep_pretrain#4]
Hello, I am trying to replicate your SFCN brain age prediction model to do my undergraduate thesis on top of it. My idea is to use your model that has great results and retrain it with part of my data and your input data. But I'm having some problems with the code, because machine learning is kind of new to me, could you share the code that was used to train the model or part of it, some parameters, anything would help? Thanks.

**Comment by ha-ha-ha-han** [comment]
Yes. Nearly there - I'll release a tutorial notebook in a week or two.

>  But I'm having some problems with the code

Can you locate the bug (if any)?

**Comment by willianpripp** [comment]
Thanks, I'll be waiting for the tutorial, apreciate a lot.

**Comment by willianpripp** [comment]
Sorry to bother, but do you have some feedback for the tutorial?
