### ISSUE TITLE
Replicating results

### ISSUE THREAD

**Issue by abanic7** [ha-ha-ha-han/UKBiobank_deep_pretrain#8]
Hello, i'm having trouble replicating results with your model. I'm using IXI database, and i'm getting MAE around 8 using the example notebook u published. Do u have any idea why is this?

**Comment by ha-ha-ha-han** [comment]
Yes. For IXI, checkout this repo and technical report:

https://www.medrxiv.org/content/10.1101/2022.12.11.22283324v2.full-text

https://github.com/PeterHolderrieth/TransferLearning_Neuroimaging
